apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: gnavi4-ingress
    namespace: sk-team-04
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    ingressClassName: public-nginx
    rules:
        - host: sk-gnavi4.skala25a.project.skala-ai.com
          http:
              paths:
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: gnavi4-backend
                            port:
                                number: 8080
                  - path: /ai
                    pathType: Prefix
                    backend:
                        service:
                            name: gnavi4-ai
                            port:
                                number: 8001
                  - path: /swagger
                    pathType: Prefix
                    backend:
                        service:
                            name: gnavi4-backend
                            port:
                                number: 8080
                  - path: /actuator
                    pathType: Prefix
                    backend:
                        service:
                            name: gnavi4-backend
                            port:
                                number: 8081
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: gnavi4-frontend
                            port:
                                number: 80
    tls:
        - hosts:
              - sk-gnavi4.skala25a.project.skala-ai.com
          secretName: sk-gnavi4-ingress-secret
